version: '2'
services:
    uml-app:
        image: uml
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://uml-postgresql:5432/UML
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    uml-postgresql:
        extends:
            file: postgresql.yml
            service: uml-postgresql
